[project]
name = "pipeline-testing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard] (>=0.118.0,<0.119.0)",
]


[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
